name: whiteboard
description: A new Flutter plugin project for tencent whiteboard.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: "2.1.5"

dev_dependencies:
  pigeon:  any

flutter:
  plugin:
    platforms:
      android:
        package: com.bond.whiteboard
        pluginClass: WhiteboardPlugin
      ios:
        pluginClass: WhiteboardPlugin